apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weekend-api.fullname" . }}
  labels:
    {{- include "weekend-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "weekend-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "weekend-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ include "weekend-api.fullname" . }}
        - secretRef:
            name: {{ include "weekend-api.fullname" . }}