apiVersion: v1
kind: Service
metadata:
  name: {{ include "weekend-api.fullname" . }}
spec:
  selector:
    {{- include "weekend-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080