replicaCount: 3

image:
  repository: weekend-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  hosts:
    - host: weekendapi.com
      paths:
        - path: /?(.*)
          pathType: Prefix
  tls: []

env:
  configs:
    APP_NAME: 
    APP_URL: 
    APP_PORT: 
    APP_ENV: 
    GIN_MODE: 
    TOKEN_AUDIENCE: 
    ACCESS_TOKEN_DURATION: 
    REFRESH_TOKEN_DURATION: 
    DB_URL: 
    DB_PORT: 
  secrets:
    DB_USER: 
    DB_PASSWORD: 
    DB_NAME: 
    TOKEN_SECRET: 
